### ISSUE TITLE
All end-user downloads should be from a proper geneontology.org domain

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#138]
Currently some products are being made available from domains not under our direct control, meaning that they leak provider information (are are thus inflexible).

Examples are:
https://s3.amazonaws.com/geneontology-public/gocam/GO-CAMs.ttl.zip
https://s3.amazonaws.com/geneontology-public/gocam/GO-CAMs.sif.zip
https://s3.amazonaws.com/geneontology-public/gocam/gocam-styles.xml

It may be simplest to sweep these into the main pipeline and expose with the rest of the products.

**Comment by kltm** [comment]
See #51

**Comment by lpalbou** [comment]
Note for https://s3.amazonaws.com/geneontology-public/gocam/gocam-styles.xml, you can copy/paste it to a release, it won't change anytime soon (styling sheet for Cytoscape)

**Comment by kltm** [comment]
Yes, something like that. Maybe drop it into go-site with the rest of the bits and bobs...

**Comment by lpalbou** [comment]
Just a few comments:
- the go site (non https) does point to the production JNL
- I wanted to do the same for the gocam site and it didn't work... because release.geneontology.org is not yet https... What is preventing this to happened ? As I understand from our last discussion, you have a CF -> S3 and as you are administering the domain with Route53, it's easy to ask for certificates. This spread of non https resource is really an issue.. and for now, I have to revert the gocam site to use a local TTL rather than the official on current.go.org
- where do you want this file https://s3.amazonaws.com/geneontology-public/gocam/gocam-styles.xml to be put ? I think it should be in products/ since this is a styling file to better display SIFs that will also be contained in that products/

**Comment by lpalbou** [comment]
Also, @kltm what is the name of the S3 bucket behind current.go.org ? You can send it by Gitter. I would like to retrieve some files from my AWS account from the S3 rather than going through HTTP requests

**Comment by kltm** [comment]
Note to self: this may no longer be an issue--catalog current product locations

**Comment by kltm** [comment]
This is redundant with https://github.com/geneontology/web-gocam/issues/24
