### ISSUE TITLE
Investigate new directory structure that bundles ontology, assocations together

### ISSUE THREAD

**Issue by cmungall** [geneontology/pipeline#14]
Currently we have `/{type}/{isodate}/artifact`

proposal is to change to `/{isodate}/{type}/artifact`

**Comment by kltm** [comment]
As it stands, your argument for the former is that ontologies and versioning could be split out at a later date from the rest of the data process.

I think it mostly hinges on whether or not that stands--the latter will be easier to work with in most ways, from indexing, to uploading, to bulk downloading; however, if the pipeline decoupling is a requirement and the former is desired we'll just make it work.

**Comment by kltm** [comment]
Okay, to restart this conversation:
1) the GO pipeline as it stands produces a single reproducible data set/product that can be treated as a single object with a single IRI (doi in the future)
2) even if an ontology pipeline cycled faster in the future, we would still bundle the ontologies used in that run with rest of the data (or bring things in with bundled bagit or catalog)
3) the issue comes down to long-term URLs for getting dated ontologies in the past from the unknown future where the frequency might be faster

Either we maintain the status quo, with issues mentioned above, or make changes like:
* we could have a separate ontology domain for ontologies--another dumping point that acts just like the way that `release` and `current` currently act
* we could just keep what we have, but have ontology-only releases (sparsely populated releases)
* keep what we have and have a single product

**Comment by kltm** [comment]
Discussion with @cmungall today.
We have decided to move the date up, which should make a bunch of the stuff we're doing easier to work with.
If, in the future, we need to have ontologies with a different schedule, we'll try the first option that we have above: mimicking something like what we have for release/current, but just for ontologies.

**Comment by kltm** [comment]
Needs check on `release`.
