### ISSUE TITLE
Will the GO-CAM site (/go-cam) function for the foreseeable future as we continue with imports, etc.?

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#190]
From @lpalbou 

I checked the public GO-CAM site and the JSON files caching the needed SPARQL queries currently takes 100kb for 2800 models. A 10x increase of GO-CAMs should have very little impact on speed. This system could scale up to 50-100k models but beyond would gain to be revisited. 

Aside from improving performances, this caching system was also put in place at the time to enable advanced search (eg term, group, author, species, date, title, etc). Basically all the things that we created with the Mineva API. 

When the number of models goes beyond 50k, we should consider boosting our efforts into having the GO-CAMs ingested (never had time to work on that but since we want to power some GO-CAM UI for the next phase/grant, would probably fit our priorities).

**Comment by kltm** [comment]
Cheers!

**Comment by kltm** [comment]
Cheers!

**Comment by lpalbou** [comment]
Just an additional note. We will have to double check there will be no timeout on the sparql endpoint when the cache is generated. Some queries were taking up to 3s, so a 10x increase could possibly time-out rdf.geneontology.org. Possibly something that I want to revisit with the gocam stats as those files should be generated by the go pipeline and not my alternate AWS pipeline.

**Comment by goodb** [comment]
Should use e.g. blazegraph-runner to run the queries on a journal file that isn't operating a Web service.  This could be added to the end of the current pipeline very easily.

**Comment by lpalbou** [comment]
I thought of that too yes. When we move that part in the pipeline it’s certainly a solution. The best would still be just to take the time to ingest gocams in golr and the more I think about it, the more it seems a priority anyhow, including for the gocam visualization and network we want. I will probably look into it after I finish a few stuffs (eg legacy infrastructure project).

Note: the cache is created through queries to the gocam api (api-gorest) which translates into sparql queries. So that’s where I can check for timeout. When I am back I will try on the dev repo - just a matter of routing the queries to the dev rdf. We will have a better idea.
