### ISSUE TITLE
Update stats in the pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#193]
A nice new version of the stats is ready to go and needs to be stepped into the pipeline.

The current PRs for this are:

https://github.com/geneontology/go-site/pull/1525
https://github.com/geneontology/pipeline/pull/191

**Comment by kltm** [comment]
Tagging @lpalbou

**Comment by kltm** [comment]
TODO:

- [ ] update #191 PR to point to go-site `stats-update`
- [ ] take pipeline PR onto `master`; test
- [ ] on `master` test success 
- [ ] merge go-site `stats-update` into `master`
- [ ] update #191 to point to `master`
- [ ] push changes into `snapshot` and `release`
- [ ] on `snapshot` test success
- [ ] trigger `release`
- [ ] on release success
- [ ] remove `-r https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-references.tsv` from stats command

**Comment by lpalbou** [comment]
Comments:
* unsure what you mean by target `stats-update` unless you want to create another branch
* ok to push both in snapshot and master
> remove -r https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-references.tsv from stats command

more like replace -r https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-references.tsv from stats command to target current.geneontology.org/release_stats/go-references.tsv

**Comment by kltm** [comment]
@lpalbou Yes, it will be a test branch before hitting master. For that test, we'll be pointing at the go-site branch.

Okay, it seems like the `-r` is a new command line option then? At least that's what it looks like to me on the diff. So the last step should then be:

replace `-r https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-references.tsv` with `-r http://current.geneontology.org/release_stats/go-references.tsv`

Is `go-references.tsv` also a new product here?

**Comment by lpalbou** [comment]
Also referencing:
* https://github.com/geneontology/go-stats/issues/12
* https://github.com/geneontology/go-stats/issues/11
* https://github.com/geneontology/go-stats/issues/10

**Comment by lpalbou** [comment]
> Okay, it seems like the -r is a new command line option then? At least that's what it looks like to me on the diff. 

That's correct, from https://github.com/geneontology/go-site/pull/1525: "_Like for the V1 of the stats, the Jenkinsfile will have to be edited again after the pipeline publishes the next release to have a more permanent link to go-references.tsv._" and https://github.com/geneontology/pipeline/pull/191: "_As the last time, once the pipeline has published a new release, we'll have to update the script to reference go-references.tsv from the release.geneontology.org and not from my temporary URL_".

> replace -r https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-references.tsv with -r http://current.geneontology.org/release_stats/go-references.tsv

Correct. 

> Is go-references.tsv also a new product here?

Yes, so is GO.uid, from https://github.com/geneontology/go-site/pull/1525: "_Note: with that PR, our pipeline can now generate the list of PMIDs to be uploaded to PubMed (see GO.uid). This was one requirement from @thomaspd and we can circle back on that when I come back to also do the actual upload for the next release. @dustine32 was handling it so he also has the info (url, user, pwd)._"

**Comment by kltm** [comment]
Perfect! I'll start rolling it out.

**Comment by kltm** [comment]
Now testing with https://github.com/geneontology/pipeline/blob/issue-193-stats-update/Jenkinsfile

**Comment by kltm** [comment]
@lpalbou The test on pipeline `master` seems to have failed.
https://build.geneontology.org/job/geneontology/job/pipeline/job/master/579/execution/node/563/log/

Before sending you on a wild goose chase, I wanted to clarify the lines in question:
https://github.com/geneontology/pipeline/blob/master/Jenkinsfile#L34 (stats-update branch)
https://github.com/geneontology/pipeline/blob/master/Jenkinsfile#L949 (added -r argument)

**Comment by lpalbou** [comment]
I saw the logs. Two things:

1) both the eutils and ebi fallback API for taxon id mapping have failed: did your server had a stable internet connexion ? is it one of the server at Berkeley ? In any case, the last failsafe was triggered and taxon labels were replaced by UNK, so it's not the reason of the fail.

2) the reason for this fail is a mistake in the Jenkins command line. The -r parameter is correct but we also have to temporarily update the -s -n parameters due to the new field by_qualifier. I did a PR on Jenkins file and should be fine for now: https://github.com/geneontology/pipeline/pull/195/files

**Comment by kltm** [comment]
Cheers--will retry with fixes from #195

**Comment by kltm** [comment]
@lpalbou 
Okay, I want to re-clarify the last step above then: 

Replace:
 `python3 /tmp/go_reports.py -g http://localhost:8080/solr/ -s https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-stats.json -n https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-stats-no-pb.json -c http://skyhook.berkeleybop.org/$BRANCH_NAME/ontology/go.obo -p http://current.geneontology.org/ontology/go.obo -r https://geneontology-archive.s3.amazonaws.com/2020-06-01/go-references.tsv -o /tmp/stats/ -d $START_DATE`
with:
`python3 /tmp/go_reports.py -g http://localhost:8080/solr/ -s http://current.geneontology.org/release_stats/go-stats.json -n http://current.geneontology.org/release_stats/go-stats-no-pb.json -c http://skyhook.berkeleybop.org/$BRANCH_NAME/ontology/go.obo -p http://current.geneontology.org/ontology/go.obo -r http://current.geneontology.org/release_stats/go-references.tsv -o /tmp/stats/ -d $START_DATE`

correct?

**Comment by lpalbou** [comment]
Yep, after we successfully produce a release with the new stats.

**Comment by kltm** [comment]
Great--applied above.

**Comment by kltm** [comment]
Testing seems to be able to move forward again, after the failures of last week. Unfortunately, continuing the test gives us:
```
15:32:15  4c - SAVING GO-STATS-SUMMARY...
15:32:15  
15:32:15  DONE.
15:32:15  
15:32:15  4d - SAVING GO-ANNOTATION-CHANGES...
15:32:15  
15:32:15  added references:   	 342
15:32:15  removed references: 	 189774
15:32:15  added pmids:        	 174
15:32:15  removed pmids:      	 120908
15:32:15  Traceback (most recent call last):
15:32:15    File "/tmp/go_reports.py", line 285, in <module>
15:32:15      main(sys.argv[1:])
15:32:15    File "/tmp/go_reports.py", line 265, in main
15:32:15      tsv_annot_changes = go_annotation_changes.create_text_report(json_annot_changes)
15:32:15    File "/tmp/go_annotation_changes.py", line 311, in create_text_report
15:32:15      evival = json_changes["detailed_changes"]["annotations"]["by_model_organism"][taxon]["by_evidence"][evidence]
15:32:15  KeyError: 'IBA'
```
I'm guessing this is due to IBAs not being available in the index as the products would have them filtered due to https://github.com/geneontology/go-site/issues/1531 . Will retry from scratch. It may be good to robustify this script so that variable and small testing GAF sets can be run through the complete pipeline.

**Comment by kltm** [comment]
@lpalbou We had the same failure as above again: https://build.geneontology.org/job/geneontology/job/pipeline/job/master/584/execution/node/563/log/ . Can this be robustified to not throw an error if all categories are not found? Currently, this is unable to pass testing on `master`. While there actually /should/ be IBAs there (https://github.com/geneontology/go-site/issues/1531#issuecomment-657967040), we generally need to be able to run the pipeline end-to-end on on any given subset of ontology and data (for testing, development, etc.). Thinking about it, we could also just wrap up the stats at the pipeline level to bypass in case of error, but that may be hard at the moment due to #183, etc. I suppose a middle groups would be catching in the python code are returning undefined for any failing element.

**Comment by kltm** [comment]
Great, @dustine32 found my error with https://github.com/geneontology/go-site/commit/cecd19b98d30ae165ffaae2b8cb5616516a8073f . 
Retesting--high hopes this time.

**Comment by lpalbou** [comment]
@kltm I will try to get something by tomorrow both for your tests and for the API calls.

**Comment by lpalbou** [comment]
@kltm added the baby proof to calls: https://github.com/geneontology/go-site/commit/c90afdf88d46f47a0c551cca2860494cba9791cc

**Comment by kltm** [comment]
Unfortunately, testing on `master` has hung up on: 
```
23:56:09  
23:56:09  4d - SAVING GO-ANNOTATION-CHANGES...
23:56:09  
23:56:09  added references:   	 351
23:56:09  removed references: 	 189743
23:56:09  added pmids:        	 182
23:56:09  removed pmids:      	 120895
23:56:09  Traceback (most recent call last):
23:56:09    File "/tmp/go_reports.py", line 284, in <module>
23:56:09      main(sys.argv[1:])
23:56:09    File "/tmp/go_reports.py", line 264, in main
23:56:09      tsv_annot_changes = go_annotation_changes.create_text_report(json_annot_changes)
23:56:09    File "/tmp/go_annotation_changes.py", line 311, in create_text_report
23:56:09      evival = json_changes["detailed_changes"]["annotations"]["by_model_organism"][taxon]["by_evidence"][evidence]
23:56:09  KeyError: 'HGI'
```

**Comment by lpalbou** [comment]
Ok, there are several things wrong here

1) that part of the code hasn't changed since october and the new script has run successfully on all previous zenodo releases, so I really was puzzled the first time it crashed 3 days ago.

2) looking more at this log and the one from 3 days ago, I just noticed that **120 895 PMIDs were removed (!)** compared to the last release, it's of course not possible. Taking a look at the go-annotation-changes.json I generated (with the new script) on the last period : https://geneontology-archive.s3.amazonaws.com/2020-05-02/go-annotation-changes.json .

<img width="311" alt="Screen Shot 2020-07-16 at 9 10 04 AM" src="https://user-images.githubusercontent.com/24249870/87695469-6423e900-c744-11ea-9f0f-991edc7361a0.png">

And on average, that's probably what to expect for this new release. Interestingly, it's not all the PMIDs (or references) that are missing, but ~75% of them. So not all the data of this new release are affected by this bug.

3) so it really looks like the stats crashes here because we have a **significant data issue with this snapshot**. I can baby proof that part of the code (gonna do that now but with warnings) but this doesn't change the PMID issue above and I am guessing a lot of annotations are just missing or incorrect in this snapshot. 

4) Is the stats the only script that give some kind of visibility on the validity of the release ? If there are other scripts, that would be interesting to check (eg GO rules ?).

5) can I get access to the full log of the stats ? It could tell more about what happened. Also, the stats script was nearly at the end and several files were generated, including the go-annotation-changes.json (not the tsv, it failed here) and the go-stats-summary.json. Those files would tell us more about what is wrong with our data.

6) in general, it would be super helpful when the pipeline crashes like that, to keep the newly generated GOLr instance  alive. A few queries would help detect issues more rapidly.

@kltm

**Comment by lpalbou** [comment]
After discussing with @dougli1sqrd , it seems you were only running a test, so that would explain the 75% missing data and the failure of the stats. In essence, some evidence codes completely disappeared between the previous release and this minimized test release. The same code works however on a normal release. If you want to run specific tests over stats, we have to discuss it and this has to be documented. As said, both the old and new code have run successfully on all zenodo releases under normal conditions.

I have baby proof again that code so that it doesn't crash when whole chunks of data are missing between two releases and added WARNING notes on top of the go-annotation-changes.tsv to notify QC of those large changes : https://github.com/geneontology/go-site/commit/1077cc2dddb1c0e2103df1c06c67a6da92b8f6c4

**Notes**:  
* at minimum, any test should contains the model organism annotations as they are directly referenced and looked for to create more advanced stats:
  * NCBITaxon:9606
  * NCBITaxon:10116
  * NCBITaxon:10090
  * NCBITaxon:3702
  * NCBITaxon:7955
  * NCBITaxon:6239
  * NCBITaxon:559292
  * NCBITaxon:7227
  * NCBITaxon:44689
  * NCBITaxon:4896
  * NCBITaxon:83333
* when we move forward with a specific set of supported species in GO (aka 142 panther species or 195 species with more than 1000 annotations), the stats would expect these species to be there.
* Internet connexion issue ? https://travis-ci.org/github/geneontology/go-site/builds/708910032

**Comment by kltm** [comment]
Okay, to clarify, previous versions of the stats were able to work on partial data, but the current version has some requirements or will not function? Unfortunately, that would require a special branch to test and branch-sensitive handling code (although not a lot at all); not necessarily a deal breaker though.

If that is that case, working from https://github.com/geneontology/pipeline/issues/193#issuecomment-657967995, once we have a better workaround for #183 we can start wrapping the stats code to bypass unless on the "release" or "snapshot" branch. Until then we could make a new branch to test against the full data set.

Assuming this is all correct, it would also be good to discuss how much effort it would take to make the stats code more robust. (Wishlist might be to have this so it could give some kind of sensible output for a NEO run, with no annotation data at all, for example.)

Tagging @pgaudet

**Comment by lpalbou** [comment]
@kltm 

The GO pipeline indeed fails a lot and that's very concerning but it has very little to do with the stats.

You mentioned some pipeline fails when calling the NCBI eutils API. I never had that issue locally and my AWS pipeline has run flawlessly since January 2019 without any intervention, maintenance or relaunch. But since doing a single API call was an issue for your production pipeline, I made that part more robust a few days after you requested it : https://github.com/geneontology/go-site/commit/c90afdf88d46f47a0c551cca2860494cba9791cc . At this stage, even if NCBI eutils is off, it won't fail.

You also had issues when doing a test with 75% missing data that was never discussed, documented or agreed. I understand it was obvious for you, but please understand that if not discussed, it does not exist in other people mind. When you indirectly asked for that new requirement 4 days ago, I paused my other projects and baby proof even more the code so it would pass a non realistic test and create text reports even if most data are suddenly missing: https://github.com/geneontology/go-site/commit/1077cc2dddb1c0e2103df1c06c67a6da92b8f6c4 . 

It is true that the text/tsv report part of the code is less robust as we have to do some hardcoded formatting to ensure a certain order and labeling of tables and columns so the file is more convenient for QC. And yes, I could have make that code more robust before so that it wouldn't crash even if we unrealistically lose 75% data and somehow still decide to proceed with a release. But it certainly wasn't a requirement and the code has never crashed under normal circumstances for normal releases.

Before criticizing my work further, may I remind you that somehow, this "non robust code" was able to run flawlessly on all zenodo releases and I even provided the files for the last two releases on day 1 ? https://github.com/geneontology/go-site/pull/1525#issue-440983611 . The same code would run on any machine, any server, but somehow it did crash on your "master" branch that you use for "testing" (!).

I did both PRs to the go-site and to the pipeline / Jenkins file to simplify your task. You literally just had to merge those PRs for the new stats to be generated. I don't know what to say.

**Comment by lpalbou** [comment]
I see that the new release was produced a few hours ago without the new stats.

For reference, the "new" stats ran again without any error on my pipeline: 
[july-2020-release.txt](https://github.com/geneontology/pipeline/files/4958055/july-2020-release.txt)

And generated this set of files (@pgaudet ):
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-stats.json
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-stats-no-pb.json
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-references.tsv
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-pmids.tsv
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-stats-summary.json
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-ontology-changes.tsv
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-ontology-changes.json
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-annotation-changes_no_pb.tsv
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-annotation-changes_no_pb.json
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-annotation-changes.tsv
https://geneontology-archive.s3.amazonaws.com/2020-07-16/go-annotation-changes.json
https://geneontology-archive.s3.amazonaws.com/2020-07-16/GO.uid

@kltm I can't understand why this code wasn't integrated in the pipeline after 24 days. We have to be able to iterate much faster on developments. I spent more time trying to get this code merged than actually coding it.

As a reminder, after this release, we are supposed to use the newly generated GO.uid file to do the monthly upload of GO PMIDs to NCBI, as asked by @thomaspd. I hope this will be simpler.

For the next release, I already created a PR to update Jenkins (https://github.com/geneontology/pipeline/pull/196) so if the code is merged, the pipeline can start generate the "new" stats in snapshots starting tomorrow.

I also updated the CHANGES.md to reflect the integration of the new stats in August: https://github.com/geneontology/go-stats/commit/67b68d2796db9def3b885665dc3a19e64a2a1e11.

**Comment by kltm** [comment]
@lpalbou I think there has been some misunderstanding and miscommunication here. We can go over how development on the pipeline works (or doesn't) and why this code has gotten caught up in it, in detail in Thursday.

**Comment by kltm** [comment]
I believe that this is now finished as the final change has migrated to the `release` pipeline: https://github.com/geneontology/pipeline/blob/7a69c74f6f735b8cc02c44af1c0db714f8a80ee6/Jenkinsfile#L976
