### ISSUE TITLE
GORULE:0000028 fails for GPAD; ensure that GPAD files can make it through QC without failing GAF-specific rules

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#280]
Currently, this means that GORULE:0000028 fails for GPAD with errors like
`WARNING - Violates GO Rule: GORULE:0000028: Found violation of: Aspect can only be one of C, P, F but was repaired -- MGI MGI:2685011 involved_in GO:0009653 PMID:26258302 ECO:0000315 MGI:MGI:4867020 20160729 MGI part_of(GO:0003183),results_in_morphogenesis_of(UBERON:0007151) contributor=https://orcid.org/0000-0001-7476-6306|model-state=production|noctua-model-id=gomodel:56aac7ad00000038`
(http://current.geneontology.org/reports/noctua_mgi-report.html#gorule-0000028)

Aspect checks do not really apply to GPAD.

Tagging @dustine32 
See https://github.com/biolink/ontobio/issues/501

**Comment by kltm** [comment]
@dustine32 This auto-closed (?), so I'm a little unsure about the status. Does this require an ontobio release and pipeline update?

**Comment by dustine32** [comment]
@kltm Yes it does! Thanks for the reminder!

I'll do the `ontobio` release and PR reqs.txt in go-site right away. So this will probably run in `snapshot` tonight?

**Comment by kltm** [comment]
@dustine32 Yes, that's correct!

**Comment by kltm** [comment]
"Testing" in `snapshot` tonight.

**Comment by dustine32** [comment]
Reporting back after the successful `snapshot` run that `GORULE:0000028` no longer is flagged in the GPAD files. Example file noctua_mgi.gpad: http://snapshot.geneontology.org/reports/noctua_mgi.report.md. This `gorule-0000028` is not even listed as being tested, which makes sense since the [code change](https://github.com/biolink/ontobio/commit/df15227656db490d4dc624b7c6570801adb40c37) skips adding the test result to the parser report object.

Comparing a non-GPAD report (ex for [mgi.gaf](http://snapshot.geneontology.org/reports/mgi.report.md)), I see that `gorule-0000028` is listed as tested but there were zero errors. This is consistent with the last release's [mgi.report.md](http://skyhook.berkeleybop.org/release/reports/mgi.report.md) results.

@kltm Thinking this is good to close now but no worries if it needs to be reopened.
