### ISSUE TITLE
GPAD/GPI products differ from GAF products

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#44]
The GPAD/GPI/GAFs in http://snapshot.geneontology.org/annotations should all contain the same information (delta their format intention) and that they should contain all legal PAINT annotations folded in.

Looking at it:

sjcarbon@moiraine:/tmp$:) cat wb.gaf | grep "[[:space:]]IBA" | cut -f 2
| sort | uniq | wc
   5675    5675   84637
sjcarbon@moiraine:/tmp$:) cat wb.gpad | grep "[[:space:]]IBA" | cut -f 2
| sort | uniq | wc
      0       0       0

It seems that there are no genes annotated by IBA in the GPAD/GPI output.
Without invoking any IBA search:

sjcarbon@moiraine:/tmp$:) cat wb.gpad | cut -f 2 | sort | uniq | wc
13506   13507  202593
sjcarbon@moiraine:/tmp$:) cat wb.gaf | cut -f 2 | sort | uniq | wc
  14090   14135  211175

It would seem that there is not a numerical match of annotated gene ids
in the two files either way (off by ~500+). It may be fine to start with
the differences there.

**Comment by dougli1sqrd** [comment]
Yes, I understand what's happening here.

Ontobio produces the combined validated GAF and validated PAINT for a group GAF dataset. Once this has been made, we read it again with the parser, in order to produce the other products (GPAD, TTL, etc). However, we have an existing rule that filters IBA evidence lines *if it's a non-paint file*. The GAF parser is currently configured to read the combined GAF product as non-paint, which means the gaf parser interprets IBAs as invalid. The solution is to tell the gafparser to read the combined GAF product *as paint*. This will prevent the filtering of the correct paint IBA annotations. 

https://github.com/biolink/ontobio/pull/202

This PR should do the trick.

**Comment by dougli1sqrd** [comment]
This is in released 1.2.4 ontobio and is fixed.
